"""
models/chat_models.py — Pydantic Data Schemas
===============================================
These models define the exact shape of data flowing IN and OUT of the API.

FastAPI uses them automatically to:
  - Validate incoming JSON (wrong type → 422 error with a clear message)
  - Serialize outgoing responses to clean JSON
  - Generate the interactive docs at /docs

Think of models as contracts:
  - Frontend knows exactly what to send
  - Backend knows exactly what it will receive and return
  - No guesswork, no silent failures

Future additions:
  - UserCreateRequest (for auth endpoints)
  - ConversationExportResponse (export full chat history)
  - AgentTaskRequest (for multi-step agentic workflows)
"""

from pydantic import BaseModel, Field, field_validator
from typing import Optional, List
from enum import Enum


# ---------------------------------------------------------------------------
# Enums — Fixed value sets
# ---------------------------------------------------------------------------

class IntentType(str, Enum):
    """
    Possible intent classifications for a user's message.
    Using an enum ensures only these exact values can appear in responses.
    """
    SIMPLE = "SIMPLE"       # Standard Q&A → handled directly by Gemini
    COMPLEX = "COMPLEX"     # Multi-step task → flagged for agent escalation


class MessageRole(str, Enum):
    """
    Message roles in a conversation thread.
    Gemini uses 'user' and 'model' (not 'assistant' like OpenAI).
    """
    USER = "user"
    MODEL = "model"         # Gemini's role name for AI messages


# ---------------------------------------------------------------------------
# Shared Sub-Models
# ---------------------------------------------------------------------------

class ConversationTurn(BaseModel):
    """
    A single message in a conversation.
    Matches Gemini's history format: role + text content.

    Example:
        {"role": "user",  "content": "What is Python?"}
        {"role": "model", "content": "Python is a programming language..."}
    """
    role: MessageRole
    content: str = Field(..., min_length=1, description="Message text content")


# ---------------------------------------------------------------------------
# Request Models (Frontend → Backend)
# ---------------------------------------------------------------------------

class ChatRequest(BaseModel):
    """
    The request body the frontend sends to POST /api/v1/chat.

    Minimum required: just a `message` string.
    Optional: session_id for memory continuity.

    Example JSON:
        {
            "message": "What is machine learning?",
            "session_id": "user-xyz-456"
        }
    """
    message: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="The user's message to the AI chatbot.",
        examples=["Hello! What can you help me with?"],
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Session identifier for multi-turn memory. Generated by backend if not provided.",
        examples=["user-abc-123"],
    )
    history: Optional[List[ConversationTurn]] = Field(
        default=None,
        description="Optional prior conversation turns. If omitted, server-side memory is used.",
    )

    @field_validator("message")
    @classmethod
    def message_not_blank(cls, v: str) -> str:
        """Ensure the message isn't just spaces or empty."""
        stripped = v.strip()
        if not stripped:
            raise ValueError("Message must contain non-whitespace characters.")
        return stripped


class ClearSessionRequest(BaseModel):
    """Request body for explicitly clearing a session (optional endpoint)."""
    session_id: str = Field(..., description="The session ID to clear from memory.")


# ---------------------------------------------------------------------------
# Response Models (Backend → Frontend)
# ---------------------------------------------------------------------------

class ChatResponse(BaseModel):
    """
    The response body the frontend receives after a chat request.

    Example JSON:
        {
            "reply": "Machine learning is a subset of AI...",
            "intent": "SIMPLE",
            "session_id": "user-xyz-456",
            "escalate": false,
            "model_used": "gemini-1.5-flash"
        }
    """
    reply: str = Field(
        ...,
        description="The AI-generated response text.",
        examples=["Hello! I'm your AI assistant. How can I help you today?"],
    )
    intent: IntentType = Field(
        default=IntentType.SIMPLE,
        description="Classified intent of the user's message.",
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Session ID — store this and send it back with every message for memory.",
    )
    escalate: bool = Field(
        default=False,
        description="True if the request was flagged as complex and escalated.",
    )
    model_used: Optional[str] = Field(
        default=None,
        description="The Gemini model that generated this response.",
    )
    turn_count: Optional[int] = Field(
        default=None,
        description="Number of conversation turns in this session.",
    )


class SessionInfoResponse(BaseModel):
    """Response for GET /chat/session/{session_id}"""
    session_id: str
    exists: bool
    turn_count: int
    message: str


class SessionClearResponse(BaseModel):
    """Response for DELETE /chat/session/{session_id}"""
    success: bool
    session_id: str
    message: str


class ErrorResponse(BaseModel):
    """
    Standardized error response structure.
    All API errors return this shape so the frontend can handle them uniformly.

    Example JSON:
        {
            "error": "Validation Error",
            "detail": "Message cannot be empty.",
            "code": 400
        }
    """
    error: str
    detail: Optional[str] = None
    code: Optional[int] = None